=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'uri'

module Wire4Client
  class SolicitudDePagosApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Registro de solicitud de pagos
    #  Se registra una solicitud de pagos. En la respuesta se proporcionará una dirección URL que lo llevará al sitio donde se le solicitará ingresar los datos de tarjeta a la que se aplicarán los cargos.
    # @param authorization Header para token
    # @param payment_request_req_dto Información de la solicitud de pagos
    # @param [Hash] opts the optional parameters
    # @return [PaymentRequestResponse]
    def register_payment_request_using_post(authorization, payment_request_req_dto, opts = {})
      data, _status_code, _headers = register_payment_request_using_post_with_http_info(authorization, payment_request_req_dto, opts)
      data
    end

    # Registro de solicitud de pagos
    #  Se registra una solicitud de pagos. En la respuesta se proporcionará una dirección URL que lo llevará al sitio donde se le solicitará ingresar los datos de tarjeta a la que se aplicarán los cargos.
    # @param authorization Header para token
    # @param payment_request_req_dto Información de la solicitud de pagos
    # @param [Hash] opts the optional parameters
    # @return [Array<(PaymentRequestResponse, Fixnum, Hash)>] PaymentRequestResponse data, response status code and response headers
    def register_payment_request_using_post_with_http_info(authorization, payment_request_req_dto, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SolicitudDePagosApi.register_payment_request_using_post ...'
      end
      # verify the required parameter 'authorization' is set
      if @api_client.config.client_side_validation && authorization.nil?
        fail ArgumentError, "Missing the required parameter 'authorization' when calling SolicitudDePagosApi.register_payment_request_using_post"
      end
      # verify the required parameter 'payment_request_req_dto' is set
      if @api_client.config.client_side_validation && payment_request_req_dto.nil?
        fail ArgumentError, "Missing the required parameter 'payment_request_req_dto' when calling SolicitudDePagosApi.register_payment_request_using_post"
      end
      # resource path
      local_var_path = '/payment-request'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])
      header_params[:'Authorization'] = authorization

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(payment_request_req_dto)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'PaymentRequestResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SolicitudDePagosApi#register_payment_request_using_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
