source "https://rubygems.org"

# Specify your gem's dependencies in examples.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
group :development, :test do
  gem 'oauth2', '~> 1.4.3'
  gem 'wire4_auth', '~> 1.1.2'
  gem 'wire4_client', '~> 1.1.2'
end
