source "https://rubygems.org"

# Specify your gem's dependencies in examples.gemspec
gemspec

gem "rake", "~> 13.0.6"
gem "rspec", "~> 3.12"
group :development, :test do
  gem 'oauth2', '~> 2.0.9'
  gem 'wire4_auth', '~> 1.1.4'
  gem 'wire4_client', '~> 1.1.4'
end
