=begin
#Wire4RestAPI

#Referencia de API. La API de Wire4 está organizada en torno a REST

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Wire4Client::BeneficiariesQueryRegisterStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BeneficiariesQueryRegisterStatus' do
  before do
    # run before each test
    @instance = Wire4Client::BeneficiariesQueryRegisterStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BeneficiariesQueryRegisterStatus' do
    it 'should create an instance of BeneficiariesQueryRegisterStatus' do
      expect(@instance).to be_instance_of(Wire4Client::BeneficiariesQueryRegisterStatus)
    end
  end
  describe 'test attribute "authorization_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "beneficiaries"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "request_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "request_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status_request"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PENDING", "AUTHORIZED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status_request = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "total_beneficiaries"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
