=begin
#Wire4RestAPI

#Referencia de API. La API de Wire4 está organizada en torno a REST

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Wire4Client::UseServiceBanking
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UseServiceBanking' do
  before do
    # run before each test
    @instance = Wire4Client::UseServiceBanking.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UseServiceBanking' do
    it 'should create an instance of UseServiceBanking' do
      expect(@instance).to be_instance_of(Wire4Client::UseServiceBanking)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ACTIVE", "INACTIVE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "use"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["WITHDRAWAL_DEPOSIT", "WITHDRAWAL", "DEPOSIT"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.use = value }.not_to raise_error
      # end
    end
  end

end
