=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for Wire4Client::CuentasDeBeneficiariosSPIDApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CuentasDeBeneficiariosSPIDApi' do
  before do
    # run before each test
    @instance = Wire4Client::CuentasDeBeneficiariosSPIDApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CuentasDeBeneficiariosSPIDApi' do
    it 'should create an instance of CuentasDeBeneficiariosSPIDApi' do
      expect(@instance).to be_instance_of(Wire4Client::CuentasDeBeneficiariosSPIDApi)
    end
  end

  # unit tests for pre_register_accounts_using_post1
  # Pre-registro de cuentas de beneficiarios SPID
  # @param request_spid_dto Información de la cuenta del beneficiario
  # @param subscription El identificador de la suscripción a esta API
  # @param [Hash] opts the optional parameters
  # @return [TokenRequiredResponse]
  describe 'pre_register_accounts_using_post1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
