=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for Wire4Client::LmitesDeMontosApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LmitesDeMontosApi' do
  before do
    # run before each test
    @instance = Wire4Client::LmitesDeMontosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LmitesDeMontosApi' do
    it 'should create an instance of LmitesDeMontosApi' do
      expect(@instance).to be_instance_of(Wire4Client::LmitesDeMontosApi)
    end
  end

  # unit tests for obtain_configurations_limits
  # Consulta las configuraciones para el contrato asocaido al enrolamiento en la aplicación
  # Consulta las configuraciones para el contrato asocaido al enrolamiento en la aplicación.
  # @param authorization Header para token
  # @param suscription Identificador de la suscripción a esta API
  # @param [Hash] opts the optional parameters
  # @return [MessageConfigurationsLimits]
  describe 'obtain_configurations_limits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_configurations
  # Actualiza las configuraciones por subscripción
  # Actualiza las configuraciones de un contrato asociado a una subscripción
  # @param authorization Header para token
  # @param suscription suscription
  # @param update_configurations_resquest_dto updateConfigurationsResquestDTO
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
