=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for Wire4Client::OperacionesCoDiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OperacionesCoDiApi' do
  before do
    # run before each test
    @instance = Wire4Client::OperacionesCoDiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OperacionesCoDiApi' do
    it 'should create an instance of OperacionesCoDiApi' do
      expect(@instance).to be_instance_of(Wire4Client::OperacionesCoDiApi)
    end
  end

  # unit tests for consult_codi_operations
  # Obtiene las operaciones generadas a partir de peticiones de pago CoDi® de forma paginada, pudiendo aplicar filtros
  # Obtiene las operaciones generadas a partir de peticiones de pago CoDi® de forma paginada, pudiendo aplicar filtros
  # @param authorization Header para token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :company_id Identificador de empresa CoDi
  # @option opts [String] :page Número de pago
  # @option opts [CodiOperationsFiltersRequestDTO] :request_filters Filtros de busqueda
  # @option opts [String] :sales_point_id Identificador del punto de venta
  # @option opts [String] :size Tamaño de pagina
  # @return [PagerResponseDto]
  describe 'consult_codi_operations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
