=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for Wire4Client::ReporteDeSolicitudesDePagosApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReporteDeSolicitudesDePagosApi' do
  before do
    # run before each test
    @instance = Wire4Client::ReporteDeSolicitudesDePagosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReporteDeSolicitudesDePagosApi' do
    it 'should create an instance of ReporteDeSolicitudesDePagosApi' do
      expect(@instance).to be_instance_of(Wire4Client::ReporteDeSolicitudesDePagosApi)
    end
  end

  # unit tests for payment_request_id_report_by_order_id_using_get
  # Consulta de solicitudes de pago por numero de orden.
  # @param authorization Header para token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_id Es el identificador de la orden a buscar.
  # @return [PaymentRequestReportDTO]
  describe 'payment_request_id_report_by_order_id_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_request_id_report_using_get
  # Consulta de solicitudes de pago por identificador de petición
  # @param authorization Header para token
  # @param request_id Identificador de la petición a buscar.
  # @param [Hash] opts the optional parameters
  # @return [PaymentRequestReportDTO]
  describe 'payment_request_id_report_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
