=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for Wire4Client::SuscripcionesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SuscripcionesApi' do
  before do
    # run before each test
    @instance = Wire4Client::SuscripcionesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuscripcionesApi' do
    it 'should create an instance of SuscripcionesApi' do
      expect(@instance).to be_instance_of(Wire4Client::SuscripcionesApi)
    end
  end

  # unit tests for change_subscription_status_using_put
  # Cambia el estatus de la suscripción
  # Se cambia el estado o estatus de la suscripción a los posibles valores que son: ACTIVE o INACTIVE
  # @param authorization Header para token
  # @param request request
  # @param subscription subscription
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'change_subscription_status_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for change_subscription_use_using_patch
  # Cambia el uso de la suscripción
  # Se asigna o cambia el uso y el estatus que se le dará a la subscripción para los servicios SPEI y SPID en el manejo de Cobros y Pagos El status puede tener los posibles valores: ACTIVE o INACTIVE. El uso puede tener los posibles valores: WITHDRAWAL_DEPOSIT o WITHDRAWAL o DEPOSIT
  # @param authorization Header para token
  # @param request request
  # @param subscription subscription
  # @param [Hash] opts the optional parameters
  # @return [ServiceBanking]
  describe 'change_subscription_use_using_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pre_enrollment_monex_user_using_post
  # Pre-registro de una suscripción
  # Pre-registra una suscripción para operar un contrato a través de un aplicación socio de la plataforma. Se retorna una dirección URL hacia el centro de autorización donde el cliente  Monex debe autorizar el acceso a los datos de su cuenta a el socio.&lt;br/&gt;&lt;br/&gt;Una vez que el cuentahabiente autorice el acceso, se envía una notificación (webhook configurado) con el evento &#39;ENROLLMENT.CREATED&#39;, el cuál contiene los datos de acceso a esta API.
  # @param authorization Header para token
  # @param pre_enrollment_data Información para la pre-suscripción
  # @param [Hash] opts the optional parameters
  # @return [PreEnrollmentResponse]
  describe 'pre_enrollment_monex_user_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_enrollment_user_using_delete
  # Elimina suscripción por su identificador.
  # Elimina una suscripción mediante su identificador. Una vez eliminada dicha suscripción, ya no se podrán realizar operaciones en el API utilizando sus credenciales
  # @param authorization Header para token
  # @param subscription El identificador de la suscripción a ésta API
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_enrollment_user_using_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_subscription_pending_status_using_delete
  # Elimina pre-registro de suscripción
  # Se elimina el pre-registro de suscripción. Sólo se elimina en caso de que el cliente Monex no haya concedido su autorización de acceso (token), es decir que la suscripcion esté pendiente.
  # @param authorization Header para token
  # @param subscription Es el identificador de la suscripción a esta API.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_subscription_pending_status_using_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
