# -*- encoding: utf-8 -*-

=begin
#Wire4RestAPI

#Referencia de la API de Wire4

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

$:.push File.expand_path("../lib", __FILE__)
require "wire4_client/version"

Gem::Specification.new do |s|
  s.name        = "wire4_client"
  s.version     = Wire4Client::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Wire4"]
  s.email       = [""]
  s.homepage    = "https://github.com/swagger-api/swagger-codegen"
  s.summary     = "Wire4RestAPI Ruby Gem"
  s.description = "Referencia de la API de Wire4"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.4'
  s.add_runtime_dependency 'json', '~> 2.6', '>= 2.6.3'

  s.add_development_dependency 'rspec', '~> 3.12'
  s.add_development_dependency 'vcr', '~> 6.2'
  s.add_development_dependency 'webmock', '~> 3.19', '>= 3.19.1'
  s.add_development_dependency 'autotest', '~> 5.0'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2.20', '>= 0.2.20'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
